import { POSITION_LABELS, TEAM_LABELS, type Player } from "../types/player";

const STATS: Array<[keyof NonNullable<Player["ratingSummary"]>, string]> = [["technique", "TEC"], ["finishing", "FIN"], ["passing", "PAS"], ["defense", "DEF"], ["stamina", "RES"], ["magic", "MAG"], ["grit", "HUE"], ["hype", "HUM"]];

export function SocialPlayerCard({ player, isMine = false, actionLabel, actionDisabled = false, onAction }: { player: Player; isMine?: boolean; actionLabel?: string; actionDisabled?: boolean; onAction?: () => void }) {
  const summary = player.ratingSummary;
  const revealed = Boolean(summary?.revealed);
  const cerro = player.team === "cerro";
  return (
    <article className={`player-card relative overflow-hidden rounded-[1.7rem] border p-4 ${cerro ? "border-blue-400/25 bg-[linear-gradient(145deg,#153f91_0%,#10213e_52%,#17131d_100%)]" : player.team === "olimpia" ? "border-white/20 bg-[linear-gradient(145deg,#e6e9ef_0%,#bcc3ce_5%,#1b2029_48%,#0e1219_100%)]" : "border-amber-300/20 bg-[linear-gradient(145deg,#2d2930,#111a29)]"}`}>
      <div className="absolute -right-8 -top-8 h-28 w-28 rounded-full bg-white/5 blur-2xl" />
      <div className="relative flex items-start justify-between gap-3"><div className="min-w-0"><p className={`text-[9px] font-black uppercase tracking-[0.2em] ${cerro ? "text-blue-200" : "text-[#bbc3d0]"}`}>{TEAM_LABELS[player.team]} {isMine && "· Mi jugador"}</p><h3 className="font-display mt-1 truncate text-3xl uppercase leading-none">{player.name}</h3><p className="mt-1 text-[10px] font-bold text-[#9aa7bb]">{player.number ? `#${player.number} · ` : ""}{POSITION_LABELS[player.preferredPosition]}</p></div><div className={`grid h-16 w-16 shrink-0 place-items-center rounded-2xl border text-center ${revealed ? "border-[#f2bd45]/40 bg-[#f2bd45]/10" : "border-white/10 bg-black/20"}`}><div><strong className="font-display block text-3xl leading-none text-[#f4c557]">{revealed ? summary?.overall : "?"}</strong><span className="text-[8px] font-black tracking-wider text-[#96a4b9]">OVR</span></div></div></div>
      {!revealed ? <div className="relative mt-5 rounded-2xl border border-dashed border-white/12 bg-black/15 p-4 text-center"><p className="text-sm font-black">🔒 Scouting en progreso</p><p className="mt-1 text-xs text-[#9ba8bc]">{summary?.voteCount ?? 0}/3 evaluaciones para revelar esta carta.</p><div className="mx-auto mt-3 h-1.5 max-w-48 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-[#f2bd45]" style={{ width: `${Math.min(100, ((summary?.voteCount ?? 0) / 3) * 100)}%` }} /></div></div> : <><p className="relative mt-4 text-[9px] font-black uppercase tracking-[0.2em] text-[#f2bd45]">🔥 Carta revelada</p><div className="relative mt-2 grid grid-cols-4 gap-1.5">{STATS.map(([field, label]) => <div key={field} className="rounded-lg bg-black/20 p-1.5 text-center"><span className="block text-[8px] font-black text-[#7889a3]">{label}</span><strong className="font-display text-lg">{Math.round(Number(summary?.[field] ?? 0) * 10)}</strong></div>)}</div>{summary?.topTrait && <div className="relative mt-3 rounded-xl bg-black/20 p-3"><p className="text-[8px] font-black uppercase tracking-wider text-[#7889a3]">Rasgo de la comunidad</p><p className="mt-1 text-sm font-extrabold text-white">“{summary.topTrait}”</p></div>}<p className="relative mt-3 text-[10px] text-[#8c9ab0]">Evaluado por {summary?.voteCount} compañeros</p></>}
      {actionLabel && <button onClick={onAction} disabled={actionDisabled} className="relative mt-4 min-h-11 w-full rounded-xl bg-white font-black text-[#111827] disabled:cursor-not-allowed disabled:bg-white/10 disabled:text-[#77859b]">{actionLabel}</button>}
    </article>
  );
}
