type TemplateGroup = "shot" | "error" | "save" | "goal" | "fatigue" | "argument" | "hype" | "skill" | "recovery" | "post" | "card" | "blooper";

export const COMMENTARY: Record<TemplateGroup, string[]> = {
  shot: [
    "{jugador} prueba desde lejos. La pelota todavía está viajando.",
    "{jugador} vio el arco. El arco aparentemente no lo vio a él.",
    "{jugador} remata con confianza. La confianza era injustificada.",
    "{jugador} le pega de primera y casi preocupa a los vecinos.",
    "{jugador} carga la pierna. El arco pide casco.",
    "Remate de {jugador}. Buena intención, pésima geografía.",
    "{jugador} busca el ángulo y encuentra el alambrado.",
    "{jugador} prueba. La pelota sale con boleto de ida.",
    "Zapatazo de {jugador}; alguien que revise el techo.",
    "{jugador} define cruzado. Demasiado cruzado.",
    "{jugador} se anima desde lejos. Valiente, sin dudas.",
    "{jugador} le pega con todo menos con dirección.",
    "El remate de {jugador} pasa saludando al arco.",
    "{jugador} intenta sorprender. Solo sorprende el resultado del remate.",
    "Tiro de {jugador}. El arquero acompaña con la mirada... porque va afuera.",
    "{jugador} saca un misil que pierde el objetivo.",
  ],
  error: [
    "{jugador} intenta salir jugando. Mala decisión.",
    "Nadie sabe qué quiso hacer {jugador}. Probablemente él tampoco.",
    "{jugador} regala una pelota peligrosísima.",
    "Control largo de {jugador}. Tan largo que ya tiene nuevo dueño.",
    "{jugador} pide calma y entrega la pelota al rival.",
    "Pase creativo de {jugador}. Creativo porque no iba para nadie.",
    "{jugador} se complica solo, una especialidad de la casa.",
    "La pelota quema y {jugador} confirma la teoría.",
    "{jugador} quiso hacer la fácil. Consiguió lo contrario.",
    "Inexplicable rechazo de {jugador}. Habrá conferencia de prensa.",
    "{jugador} pierde una pelota con peligro incluido.",
    "Se desconectó el joystick de {jugador} por un instante.",
    "{jugador} inventa un problema donde no había ninguno.",
    "Pifia de {jugador}. El césped se declara inocente.",
    "{jugador} toma una decisión dudosa y la ejecuta peor.",
    "Error de {jugador}. De esos que terminan en el grupo de WhatsApp.",
  ],
  save: [
    "¡ATAJADÓN de {arquero}!",
    "{arquero} aparece justo cuando parecía gol.",
    "{arquero} se convierte momentáneamente en Neuer.",
    "Manotazo salvador de {arquero}.",
    "{arquero} achica y gana el duelo.",
    "Tremenda respuesta de {arquero}. Sigue con vida su equipo.",
    "{arquero} vuela para la foto y, de paso, ataja.",
    "Reflejos felinos de {arquero}; felino con poca elongación, pero felino.",
    "{arquero} baja la persiana.",
    "Otra atajada de {arquero}, que ya pide aumento.",
    "{arquero} pone el cuerpo y salva lo que era gol.",
    "Providencial {arquero} debajo de los tres palos.",
    "{arquero} dice que no con una mano firme.",
    "Gran tapada de {arquero}. Hasta él parece sorprendido.",
    "{arquero} sostiene al equipo con guantes imaginarios.",
    "Respuesta enorme de {arquero} en el mano a mano.",
  ],
  goal: [
    "¡GOOOOOOOL DE {equipo}! {jugador} la manda a guardar.",
    "¡GOL DE {equipo}! {jugador} define como si supiera.",
    "Golazo de {jugador}. Nadie esperaba esto.",
    "{jugador} encuentra el hueco y factura para {equipo}.",
    "¡Adentro! {jugador} rompe el cero.",
    "{jugador} no perdona. Esta frase jamás había sido escrita sobre él.",
    "¡Gol de {jugador}! Silencio del lado rival.",
    "{jugador} empuja la pelota y sale a festejar una obra colectiva.",
    "Definición quirúrgica de {jugador}. Sin anestesia.",
    "¡GOOOL! {jugador} la cruza y desata el delirio.",
    "{jugador} convierte y ya prepara el mensaje para el grupo.",
    "Toque sutil de {jugador}. La pelota besa la red.",
    "{jugador} aprovecha el regalo y no devuelve nada.",
    "¡Qué gol de {jugador}! Por cinco segundos esto pareció profesional.",
    "{jugador} define fuerte y abajo. Manual básico, resultado perfecto.",
    "¡Gol de {equipo}! {jugador} estaba donde tenía que estar.",
    "{jugador} saca un remate imposible y entra.",
    "La red se mueve: {jugador} acaba de marcar para {equipo}.",
    "{jugador} la pone contra un palo. Festejo cinematográfico.",
    "¡GOOOOOOL! {jugador} convierte una chance que parecía perdida.",
    "{jugador} firma el gol con tinta indeleble y botines prestados.",
    "Pelota al fondo de la red. El responsable: {jugador}.",
  ],
  fatigue: [
    "{jugador} empieza a negociar con sus pulmones.",
    "{jugador} ya está mirando el reloj.",
    "La resistencia de {jugador} acaba de presentar su renuncia.",
    "{jugador} corre menos y gesticula más.",
    "Las piernas de {jugador} entraron en modo ahorro de energía.",
    "{jugador} pide el cambio con una mirada muy clara.",
    "{jugador} descubre que cuarenta minutos sí eran muchos.",
    "El tanque de {jugador} marca reserva.",
    "{jugador} respira como si hubiera subido diez pisos.",
    "Cada pique de {jugador} ahora requiere una reunión previa.",
    "{jugador} empieza a defender con posicionamiento... desde muy lejos.",
  ],
  argument: [
    "{jugador} discute una falta que vio solamente él.",
    "Pequeña cumbre diplomática encabezada por {jugador}.",
    "{jugador} protesta con argumentos, volumen y cero pruebas.",
    "Hay debate en cancha. {jugador} no acepta mociones.",
    "{jugador} reclama mano. Era su propia mano.",
    "Todos hablan al mismo tiempo. {jugador} parece llevar la presidencia.",
    "{jugador} exige justicia inmediata y un tiro libre.",
    "Discusión caliente; la pelota espera pacientemente.",
    "{jugador} presenta una apelación verbal de larga duración.",
    "Se arma el comité de reclamos. {jugador} toma la palabra.",
    "{jugador} jura que fue pelota. Nadie le cree.",
  ],
  hype: [
    "{jugador} pide la pelota como si estuviera jugando una final de Libertadores.",
    "{jugador} señala tres movimientos distintos y después se queda quieto.",
    "{jugador} reclama protagonismo. La pelota todavía no fue consultada.",
    "{jugador} acomoda a todo el equipo con autoridad de técnico interino.",
    "{jugador} levanta los brazos: quiere la pelota, la cámara y el relato.",
    "{jugador} promete una jugada histórica. Empieza con un pase atrás.",
    "{jugador} da indicaciones como si hubiera estudiado al rival toda la semana.",
    "{jugador} ensaya una mirada épica antes de un lateral.",
  ],
  skill: [
    "{jugador} tira un lujo y, contra todo pronóstico, funciona.",
    "Caño de {jugador}. Hay que cerrar la cancha.",
    "{jugador} deja a uno pagando y sigue la jugada.",
    "Giro elegante de {jugador}. Un segundo de fútbol champagne.",
    "{jugador} esconde la pelota con una maniobra deliciosa.",
    "Amague de {jugador}; el defensor compra entrada completa.",
    "{jugador} se inventa un pasillo donde no lo había.",
    "Pisadita y salida de {jugador}. Aplausos de la tribuna imaginaria.",
    "{jugador} prende la consola y supera a su marca.",
    "Gran jugada individual de {jugador}. Que alguien la grabe.",
    "{jugador} se viste de diez durante unos segundos.",
  ],
  recovery: [
    "{jugador} mete la pierna y recupera una pelota clave.",
    "Quite limpio de {jugador}. Fútbol y sacrificio.",
    "{jugador} huele el peligro y corta justo a tiempo.",
    "Recuperación de {jugador}; empieza la contra.",
  ],
  post: [
    "¡PALO! {jugador} estuvo a centímetros de gritarlo.",
    "El poste le niega el gol a {jugador}.",
    "Remate de {jugador} al metal. Se salvó {rival}.",
  ],
  card: [
    "Tarjeta para {jugador}. Llegó tarde y con equipaje.",
    "{jugador} se gana una tarjeta por exceso de entusiasmo.",
    "Falta táctica de {jugador}. Táctica, pero bastante evidente.",
  ],
  blooper: [
    "Blooper de {jugador}. Esto tendrá repetición en cámara lenta.",
    "{jugador} protagoniza una escena difícil de explicar.",
    "Momento insólito de {jugador}. El fútbol amateur en estado puro.",
  ],
};

export function commentaryLine(group: TemplateGroup, random: () => number, values: Record<string, string>): string {
  const options = COMMENTARY[group];
  const template = options[Math.floor(random() * options.length)] ?? options[0];
  return Object.entries(values).reduce((line, [key, value]) => line.replaceAll(`{${key}}`, value), template);
}
